image_root: 'datasets/RSTPReid/imgs'
ann_root: 'annotation'
dataset: 'retrieval_rstp'

# set pretrained as a file path or an url
pretrained: 'checkpoint/model_base.pth'

# size of vit model; base or large

vit: 'base'
batch_size_train: 12
batch_size_test: 32
vit_grad_ckpt: True
vit_ckpt_layer: 6
init_lr: 1e-5

# vit: 'large'
# batch_size_train: 16
# batch_size_test: 32
# vit_grad_ckpt: True
# vit_ckpt_layer: 12
# init_lr: 5e-6

image_size: 224
queue_size: 3600
alpha: 0.4
k_test: 128
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 20

